# Generated by Django 5.2.7 on 2025-11-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chimneydesign',
            name='original_file',
            field=models.FileField(blank=True, help_text='Original uploaded file (STEP or GLB)', null=True, upload_to='models/original/'),
        ),
        migrations.AddField(
            model_name='chimneydesign',
            name='original_file_format',
            field=models.CharField(blank=True, help_text='Format of original file (STEP, GLB, etc.)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chimneydesign',
            name='model_file',
            field=models.FileField(blank=True, help_text='GLB format file', null=True, upload_to='models/'),
        ),
    ]
