# Generated by Django 5.2.7 on 2025-11-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chimneydesign_original_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='project_thumbnails/'),
        ),
    ]
