# Generated by Django 4.2.7 on 2025-12-08 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_thumbnail_to_userproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chimneydesign',
            name='model_file',
            field=models.FileField(blank=True, help_text='Model file (GLB or STEP format only)', null=True, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='chimneydesign',
            name='original_file',
            field=models.FileField(blank=True, help_text='Original uploaded file (GLB or STEP format only)', null=True, upload_to='models/original/'),
        ),
        migrations.AlterField(
            model_name='chimneydesign',
            name='original_file_format',
            field=models.CharField(blank=True, help_text='Format of original file (GLB or STEP only)', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='DesignGLBFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='GLB or GLTF file', upload_to='models/')),
                ('file_type', models.CharField(choices=[('model', 'Model File'), ('original', 'Original File')], default='model', help_text='Type of file (model or original)', max_length=20)),
                ('file_name', models.CharField(blank=True, help_text='Original filename', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary file to use for 3D viewer')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glb_files', to='api.chimneydesign')),
            ],
            options={
                'verbose_name': 'Design GLB File',
                'verbose_name_plural': 'Design GLB Files',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
