# Generated by Django 4.2.7 on 2025-12-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_chimneydesign_model_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chimneydesign',
            name='position_x',
            field=models.FloatField(default=0.0, help_text='X position'),
        ),
        migrations.AddField(
            model_name='chimneydesign',
            name='position_y',
            field=models.FloatField(default=0.0, help_text='Y position'),
        ),
        migrations.AddField(
            model_name='chimneydesign',
            name='position_z',
            field=models.FloatField(default=0.0, help_text='Z position'),
        ),
        migrations.AddField(
            model_name='chimneydesign',
            name='rotation_x',
            field=models.FloatField(default=0.0, help_text='X rotation in degrees'),
        ),
        migrations.AddField(
            model_name='chimneydesign',
            name='rotation_y',
            field=models.FloatField(default=0.0, help_text='Y rotation in degrees'),
        ),
        migrations.AddField(
            model_name='chimneydesign',
            name='rotation_z',
            field=models.FloatField(default=0.0, help_text='Z rotation in degrees'),
        ),
        migrations.AddField(
            model_name='chimneydesign',
            name='scale_x',
            field=models.FloatField(default=1.0, help_text='X scale'),
        ),
        migrations.AddField(
            model_name='chimneydesign',
            name='scale_y',
            field=models.FloatField(default=1.0, help_text='Y scale'),
        ),
        migrations.AddField(
            model_name='chimneydesign',
            name='scale_z',
            field=models.FloatField(default=1.0, help_text='Z scale'),
        ),
    ]
