# Generated by Django 5.2.7 on 2025-11-25 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('customer_code', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('drawing_type', models.CharField(blank=True, choices=[('shop', 'Shop Drawing'), ('production', 'Production Drawing'), ('both', 'Both')], max_length=20)),
                ('sheet_type', models.CharField(blank=True, choices=[('202', 'Sheet 202'), ('304', 'Sheet 304')], max_length=10)),
                ('dim_section1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dim_section2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dim_section3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dim_section4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exhaust_collar_dm', models.CharField(blank=True, max_length=100)),
                ('filter_item_code', models.CharField(blank=True, max_length=100)),
                ('filter_dimension', models.CharField(blank=True, max_length=100)),
                ('filter_qty', models.IntegerField(blank=True, null=True)),
                ('filter_length', models.CharField(blank=True, max_length=100)),
                ('watts', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cmh_cfm', models.DecimalField(blank=True, decimal_places=2, help_text='CMH/CFM airflow measurement', max_digits=10, null=True)),
                ('collar_static_pressure', models.DecimalField(blank=True, decimal_places=2, help_text='Static pressure at collar', max_digits=10, null=True)),
                ('fresh_air_qty', models.DecimalField(blank=True, decimal_places=2, help_text='Fresh air quantity at collar', max_digits=10, null=True)),
                ('front_panel_thickness', models.DecimalField(blank=True, decimal_places=2, help_text='Front panel thickness', max_digits=10, null=True)),
                ('skin_type', models.CharField(blank=True, choices=[('single', 'Single Skin'), ('double', 'Double Skin')], help_text='Single or double skin', max_length=20)),
                ('make', models.CharField(blank=True, help_text='Manufacturer/brand', max_length=255)),
                ('uv_lamp_cutout', models.BooleanField(default=False, help_text='UV Lamp Cutout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
