# Generated by Django 5.2.7 on 2025-11-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_item_model_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='model_subtype',
        ),
        migrations.AddField(
            model_name='item',
            name='model_type',
            field=models.CharField(blank=True, choices=[('WMSS', 'WMSS'), ('WMSP', 'WMSP'), ('WMDS', 'WMDS'), ('WMC', 'WMC'), ('UVC', 'UVC'), ('ISS', 'ISS'), ('ISP', 'ISP'), ('IDS', 'IDS'), ('IC', 'IC')], help_text='Chimney model type (WMSS, WMSP, WMDS, WMC, UVC, ISS, ISP, IDS, IC)', max_length=10),
        ),
    ]
