# Generated by Django 5.2.7 on 2025-11-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_item_model_subtype_item_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='model_type',
            field=models.CharField(blank=True, choices=[('WMSS', 'WALL MOUNTED SKIN'), ('WMSP', 'WALL MOUNTED SINGLE PLENUM'), ('WMDS', 'WALL-MOUNTED DOUBLE SKIN'), ('WMC', 'WALL-MOUNTED COMPENSATING'), ('UVC', 'UV COMPENSATING'), ('ISS', 'ISLAND SINGLE SKIN'), ('IDS', 'ISLAND DOUBLE SKIN'), ('IC', 'ISLAND COMPENSATING')], help_text='Chimney model type', max_length=10),
        ),
    ]
