# Generated by Django 5.2.7 on 2025-11-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_item_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dim_section5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
