# Generated by Django 5.2.7 on 2025-11-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_dim_section5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uv_lamp_cutout',
            field=models.CharField(blank=True, help_text='UV Lamp Cutout (610, 842, 1200, 1554)', max_length=20),
        ),
    ]
